apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: httpserver-test
  namespace: default
spec:
  maxReplicas: 10
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 10
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpserver-test